apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prod
  namespace: argocd
spec:
  project: guestbook-project
  source:
    repoURL: https://github.com/andregri/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
