apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rootapps-project
  namespace: argocd
  # Finalizer: ensures that project is not deleted until it is not referenced by any application
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Creating Project Root Apps Child
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: apps-infra
    server: https://kubernetes.default.svc
  - namespace: guestbook-dev
    server: https://kubernetes.default.svc
  - namespace: guestbook-prod
    server: https://kubernetes.default.svc
  - namespace: guestbook
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.deafult.svc
