kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: poc-nfs-claim #demo-claim
  namespace: nfs-provisioning
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi