apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring-project
  namespace: argocd
  # Finalizer: ensures that project is not deleted until it is not referenced by any application
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Creating Project Monitoring
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: monitoring
    server: https://kubernetes.default.svc
