apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: v2.47.0
    argocd.argoproj.io/instance: prometheus-dev
    helm.sh/chart: prometheus-25.3.1
  name: prometheus-dev-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-dev-server
subjects:
  - kind: ServiceAccount
    name: prometheus-dev-server
    namespace: monitoring
