apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: prometheus-dev
    app.kubernetes.io/name: alertmanager
  name: storage-prometheus-dev-alertmanager-0
  namespace: monitoring-ns
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
