apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-kube
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.3.1
    helm:
      values: |
        pushgateway:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true